#!/usr/bin/Rscript


#BiocManager::install("Rsamtools")

library(BSgenome)

get_seqtype_conversion_lookup()



library(BSgenome.Hsapiens.UCSC.hg19)
library(Rsamtools)
install.packages("")

getwd()
setwd("d:/github/Rani_Perasani/snEffect/Rani_Perasani/")
uma<-read.table(file = "uma_example.txt",header = T,sep="\t")
library(tidyverse)
uma<-as_tibble(uma)
colnames(uma)
uma_vcf<-uma%>%select(Chrom,Position,Sample.Name,Ref,Variant,Quality,Filter)
uma_vcf$INFO<-NULL
uma_vcf
colnames(uma_vcf)<-c("CHROM","POS","ID","REF","ALT","QUAL","FILTER","INFO")                            
write.table(uma_vcf, "uma_example.vcf", sep = "\t",quote = F,row.names = F)
